export const sectionTitles = [
  'software',
  'overview',
  'introduction',
  'power supply',
  'intelligent',
  'warranty',
  'licensing',
  'stacking',
  'highlights',
  'platform',
  'status',
  'scalability',
  'features',
  'specifications',
  'ordering',
  'configurations',
  'part numbers',
  'milestones',
  'performance',
];
